# Generated by Django 5.1 on 2024-08-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dispositivo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('esta_disponible', models.BooleanField(default=True)),
            ],
            
            options={
                'db_table': 'dispositivos_info',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('telefono_estudiante', models.CharField(max_length=15)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='mi_servicio.dispositivo')),
            ],

            options={
                'db_table': 'prestamos_info',
            },
        ),
    ]
